// Code generated by melt; DO NOT EDIT.

package templates

import (
	"github.com/0-mqix/melt"
	"io"
	"net/http"
)

var (
	ComponentsHeader   *melt.Component
	Index              *melt.Component
	Login              *melt.Component
	ComponentsOverview *melt.Component
)

type GlobalHandlers struct {
}

func Load(furnace *melt.Furnace, handlers GlobalHandlers) {
	ComponentsHeader = furnace.MustGetComponent("templates/components/header.html")
	Index = furnace.MustGetComponent("templates/index.html")
	Login = furnace.MustGetComponent("templates/login.html")
	ComponentsOverview = furnace.MustGetComponent("templates/components/overview.html")

	globalHandlers := make(map[string]melt.GlobalHandler)

	furnace.SetGlobalHandlers(globalHandlers)
}

type ComponentsHeaderData struct {
	Swap    any
	Balance any
}

// generated write function for component
//
//	path: "templates/components/header.html"
func WriteComponentsHeader(w io.Writer, r *http.Request, data ComponentsHeaderData, globalOptions ...melt.GlobalOption) error {
	return ComponentsHeader.Write(w, r, data, globalOptions...)
}

type IndexData struct {
	Swap              any
	Balance           any
	Assets            any
	PriceUsd          any
	ChangePercent24Hr any
	Wallet            any
}

// generated write function for component
//
//	path: "templates/index.html"
func WriteIndex(w io.Writer, r *http.Request, data IndexData, globalOptions ...melt.GlobalOption) error {
	return Index.Write(w, r, data, globalOptions...)
}

type IndexAssetData struct {
	Name    any
	Balance any
	Id      any
	Symbol  any
}

// generated write function for a template in a component
//
//	path: "templates/index.html"
//	template: "asset"
func WriteIndexAsset(w io.Writer, data IndexAssetData) error {
	return Index.WriteTemplate(w, "asset", data)
}

type LoginData struct{}

// generated write function for component
//
//	path: "templates/login.html"
func WriteLogin(w io.Writer, r *http.Request, data LoginData, globalOptions ...melt.GlobalOption) error {
	return Login.Write(w, r, data, globalOptions...)
}

type ComponentsOverviewData struct {
	Coin  any
	Asset any
}

// generated write function for component
//
//	path: "templates/components/overview.html"
func WriteComponentsOverview(w io.Writer, r *http.Request, data ComponentsOverviewData, globalOptions ...melt.GlobalOption) error {
	return ComponentsOverview.Write(w, r, data, globalOptions...)
}
